### ISSUE TITLE
Lab 1 notebook can't import tensorflow module

### ISSUE THREAD

**Issue by JDLH** [yala/introdeeplearning#4]
When I try running Lab 1  according to the instructions and code in the Lab1 ipython notebook, [Lab1.ipynb](https://github.com/yala/introdeeplearning/blob/master/Lab1.ipynb), the import fails.

It turns out that although I followed the setup instructions in [README.md](https://github.com/yala/introdeeplearning/blob/master/README.md), the ipython instance was using my system-level Python interpreter and libraries, instead of the local ones within the virtualenv. 

The solution for me was to execute this shell command, 

`python -m ipykernel install --user --name=intro_dl`

before running `jupyter notebook`. Further instructions [here](http://help.pythonanywhere.com/pages/IPythonNotebookVirtualenvs).

(I am a member of the public following along with 6.S191 from outside MIT. Thank you for making it available!)

**Comment by yala** [comment]
This seems to fix it for the pip setup, i'll investigate if this applies for the conda installation before closing the issue.
